<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCz0XWt7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCz0XWt7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCz0XWt7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCz0XWt7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCz0XWt7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cz0XWt7',
    'container.build_id' => 'e24e3dab',
    'container.build_time' => 1681077526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCz0XWt7');
