<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJeOxz2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJeOxz2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJeOxz2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJeOxz2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJeOxz2\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJeOxz2',
    'container.build_id' => 'c2a6dbbb',
    'container.build_time' => 1680382796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJeOxz2');
