<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAdkbpYT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAdkbpYT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAdkbpYT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAdkbpYT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAdkbpYT\App_KernelDevDebugContainer([
    'container.build_hash' => 'AdkbpYT',
    'container.build_id' => '17de294a',
    'container.build_time' => 1680382132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAdkbpYT');
